### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by stefan-reich** [abahgat/suffixtree#6]
I like that you made this.

Here's a question: Is it normal that suffix trees are huge? I made a GeneralizedSuffixTree for a text with 7.8K characters (some source code) and it consumed 19 MB in memory.

I thought Ukkonen's algorithm was O(n) in space? What's going on?

So... is there room for optimization? Can identical parts of the tree be merged? It seems you are doing something like that already.

Many greetings

**Comment by abahgat** [comment]
Hi Stefan,
thank you for your comment.
In short, yes, it's common for suffix tree to take much more memory than the string(s) that they are built to index, and Ukkonen's algorithm is no exception, unfortunately.

The advantage of Ukkonen's algorithm comes from it being on-line (meaning it can build and update an index character by character) and its O(n) *runtime* complexity for most alphabets (space complexity is still super-linear).

As far as optimizations go, you can find some information about why I did on this [page](https://www.abahgat.com/project/suffix-tree/).

Hope this helps!
Alessandro

**Comment by stefan-reich** [comment]
Thanks for your answer!

However, I think O(n) runtime also implies O(n) space as it is assumed that allocating a memory cell takes time.

So something must be wrong in the terminology...?

Many greetings

**Comment by abahgat** [comment]
Yes, you are right.

That said, I have found high memory usage to be consistent with the shape of the tree being constructed.

There still may be room for memory optimization beyond the things I tried and mentioned in the link above. Basically I stopped optimizing when I could fit the index I was working with in the memory budget I had when I wrote this.

I would be curious to hear if you find out anything new!

Thanks

**Comment by stefan-reich** [comment]
I'd be curious to know what your application for this library was? I am not quite clear where a suffix tree would ever beat something as optimized as String.contains().

Thanks

**Comment by abahgat** [comment]
Sure!

Originally, the use case was quite artificial and it came from a programming puzzle where I had to implement instant search over a pretty large text dictionary ([backstory](https://www.abahgat.com/blog/the-programming-puzzle-that-got-me-my-job/)).

At least in that case, an implementation based on `contains` was significantly slower.

I know of a few more folks that used this library for similar instant search use cases, but most of the users I spoke with never disclosed what they were looking to do.

**Comment by stefan-reich** [comment]
Well that was a good read!

I'm actually a Xoogler myself, albeit it my stay was short (less than a year around 2009).

I'm still trying to understand suffix trees fully. I'm thinking there might be an intermediate structure that allows to search strings of a limited size instantly.

Hold on, why not just make a hash index of n-grams?

Then again, I am trying to beat a time of 10 ms that String.contains() takes searching my whole code repository (45 MB), so possibly not really worth it. I do love instant searches though :D

Many greetings

**Comment by abahgat** [comment]
Thanks!
2009? We wouldn't have overlapped then, I joined in 2012.

I suppose a hash index may work if you cap the maximum length of the n-grams you expect to look up to a small n. Suffix trees tend to handle long strings pretty well because they are [compressed tries](https://en.wikipedia.org/wiki/Trie#Compressing_tries).
In general, suffix trees are great data structures in theory but their memory behavior tends to run into issues when confronted with modern memory architectures (i.e. layered caches, etc). 

For comparison with your use case, I believe the data set I indexed with this implementation was ~400Mb, the whole application was using ~1Gb (the majority of which was taken by the tree) and searches were completing in less than 0.1ms.

**Comment by stefan-reich** [comment]
Hey, I am surprisingly deep into suffix trees myself now. My goal is to index the complete English Wikipedia (70 GB) with a  search engine taking ~1 ms for any query.

I have a compression step that takes place first, then a suffix tree is built over the compressed representation.

It's all great, but my suffix tree construction is probably too slow right now. I am using a fairly naive algorithm. I might want to use your implementation if it wasn't so memory-hungry.

BTW could the reason for that be that your Edge class contains a String?

**Comment by stefan-reich** [comment]
I think I'll walk through your code and try to duplicate its operation

**Comment by stefan-reich** [comment]
I made another suffix tree generator work - but it now seems I'll do without suffix trees and achieve superfast search anyway.

**Comment by abahgat** [comment]
Cool, what did you end up using in the end?

Regarding the question here

> BTW could the reason for that be that your Edge class contains a String? The usual storage method with suffix trees is to only store (from; to) pairs of integer indices into the full string.

I didn't think this was the case when I tested this library since the `String` implementation in Java does pooling and string interning, which effectively mean it allocated one array of characters for each indexed string and each substring was constructed via a reference to the same array of characters and start/end indices.

Would certainly be worth checking against an updated memory dump to confirm this is still the behavior with newer version of Java though.

**Comment by stefan-reich** [comment]
True, if you did the project before 1.7.0_06, you were using the older virtual substring logic.

Actually my search engine project just went closed source :) I think I found a pretty cool secret sauce and this time I will not open source it, at least not initially.

My current results are 4 ms for searches in 1 GB of text. Very curious how it will scale from here. Ultimately, I have to make index files on disk because my server's main memory (32 GB) is not big enough to hold the whole indexed Wikipedia. So I have to manage hash tables and stuff in files which is work to implement... Or maybe I'll look for a library for that. Surely there is some optimized on-disk hashtable for Java?
